### Numpy Solutions
###### > >  Hacker Rank
> https://www.hackerrank.com/domains/python?filters%5Bsubdomains%5D%5B%5D=numpy&badge_type=python

###### Arrays
> https://www.hackerrank.com/challenges/np-arrays/problem


In [1]:
def arrays(arr):
    return numpy.array(arr[::-1],float)

###### > Shape & Reshape
> https://www.hackerrank.com/challenges/np-shape-reshape/problem

In [5]:
import numpy as np
n = list(map(int,input('').split()))
print(np.array(n).reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


###### > Transpose & Flatten
> https://www.hackerrank.com/challenges/np-transpose-and-flatten/problem

In [6]:
import numpy as np
a = list(map(int,input('').split()))
x = []
for i in range(a[0]):
    b = list(map(int,input('').split()))
    x.append(b)
print(np.array(x).T)
print((np.array(x).flatten()))

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


###### > Concatenate
> https://www.hackerrank.com/challenges/np-concatenate/problem

In [ ]:
import numpy as np
a = list(map(int,input('').split()))
x = []; xx =[]
for i in range(a[0]):
    b = list(map(int,input('').split()))
    x.append(b)
for i in range(a[1]):
    bb = list(map(int,input('').split()))
    xx.append(bb)
ar1 = np.array(x)
ar2 = np.array(xx)
print(np.concatenate((ar1,ar2),axis=0))

###### > Zeros & Ones
> https://www.hackerrank.com/challenges/np-zeros-and-ones/problem

In [ ]:
import numpy as np
q = []
shape = input().split()
for i in shape:
    i = int(i)
    q.append(i)
#print(q)
t = tuple(q)
print(np.zeros(t,dtype=int))
print(np.ones(t,dtype=int))

###### > Eye or Identity
> https://www.hackerrank.com/challenges/np-eye-and-identity/problem

In [ ]:
import numpy
print(str(numpy.eye(*map(int,input().split()))).replace('1',' 1').replace('0',' 0'))

###### >>Array Mathematics
> https://www.hackerrank.com/challenges/np-array-mathematics/problem

In [ ]:
import numpy as np
N,M = map(int,input('').split())
A = [];B = []
for i in range(N):
    A.append(list(map(int,input('').split())))
for i in range(N):
    B.append(list(map(int,input('').split())))
A = np.array(A);B=np.array(B)
print(np.add(A,B))
print(np.subtract(A,B))
print(np.multiply(A,B))
print(A//B)
print(np.mod(A,B))
print(np.power(A,B))

###### > Floor , Ceil , Rint
> https://www.hackerrank.com/challenges/floor-ceil-and-rint/problem

In [ ]:
import numpy
numpy.set_printoptions(sign=' ')
a = numpy.array(input().split(),float)
print(numpy.floor(a))
print(numpy.ceil(a))
print(numpy.rint(a))

###### > Sum and Product
> https://www.hackerrank.com/challenges/np-sum-and-prod/problem

In [ ]:
import numpy as np
a = np.array(input('').split(),int)
Arr =[]
for i in range(a[0]):
    Arr.append(list(map(int,input('').split())))
AS = np.sum(Arr,axis=0)
print(np.prod(AS))

###### > Min and Max
> https://www.hackerrank.com/challenges/np-min-and-max/problem

In [ ]:
import numpy as np
a = np.array(input('').split(),int)
Arr =[]
for i in range(a[0]):
    Arr.append(list(map(int,input('').split())))
m = np.min(Arr,axis=1)
print(np.max(m))

###### > Mean , Variance , Std
> https://www.hackerrank.com/challenges/np-mean-var-and-std/problem

In [ ]:
import numpy as np
np.set_printoptions(sign=' ')
a = np.array(input('').split(),int)
Arr =[]
for i in range(a[0]):
    Arr.append(list(map(int,input('').split())))
print(np.mean(Arr,axis=1))
print(np.var(Arr,axis=0))
print(round(np.std(Arr),12))

###### > Dot and Cross product
> https://www.hackerrank.com/challenges/np-dot-and-cross/problem

In [ ]:
import numpy as np
N = int(input())
Arr = [];Brr = []
for i in range(N):
    Arr.append(list(map(int,input('').split())))
for i in range(N):
    Brr.append(list(map(int,input('').split())))
print(np.dot(Arr,Brr))

###### > Inner and Outer 
> https://www.hackerrank.com/challenges/np-inner-and-outer/problem

In [ ]:
import numpy as np
A = list(map(int,input('').split()))
B = list(map(int,input('').split()))
print(np.inner(A,B))
print(np.outer(A,B))

###### > Polynomials
> https://www.hackerrank.com/challenges/np-polynomials/problem

In [ ]:
import numpy as np
P = list(map(float,input().split()))
x = float(input())
print(np.polyval(P,x))

###### > Linear Algebra
> https://www.hackerrank.com/challenges/np-linear-algebra/problem

In [ ]:
import numpy as np
N = int(input())
A=[]
for i in range(N):
    A.append(list(map(float,input().split())))
print(round(np.linalg.det(A),2))